# Generated by Django 5.1.2 on 2024-11-06 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='is_super_admin',
            new_name='is_blog_admin',
        ),
    ]
