# Generated by Django 5.1.2 on 2024-11-07 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_remove_products_additional_images_and_more'),
        ('shopping_cart', '0002_alter_cartitem_product'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Products',
        ),
    ]
