# Generated by Django 5.1.2 on 2024-11-07 10:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneralSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_ordering_enabled', models.BooleanField(default=True)),
                ('is_full_payment_enabled', models.BooleanField(default=True)),
                ('is_down_payment_enabled', models.BooleanField(default=True)),
                ('is_maintenance_mode', models.BooleanField(default=False)),
                ('maintenance_message', models.TextField(blank=True, null=True)),
                ('order_disabled_message', models.TextField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
